### ISSUE TITLE
Question regarding data source

### ISSUE THREAD

**Issue by ruchernchong** [ppvbc/ppvbc.github.io#1]
Where does this data source come from? Is it from an actual API or you have scraped it from somewhere? 

If possible, may I use the data?

**Comment by FishPain** [comment]
I too have the same question. I think it is static data as of now. It will also be nice for you to explain the difference between locations highlighted in orange and those that are not highlighted on the web page.

**Comment by chpeck** [comment]
> Where does this data source come from? Is it from an actual API or you have scraped it from somewhere?
> 
> If possible, may I use the data?

I manually enter them when the information is released from MOH. What would you be using the data for?

**Comment by chpeck** [comment]
> I too have the same question. I think it is static data as of now. It will also be nice for you to explain the difference between locations highlighted in orange and those that are not highlighted on the web page.

Ah yes, I added the badge for "New". It should be live on site now.

**Comment by ruchernchong** [comment]
> > I too have the same question. I think it is static data as of now. It will also be nice for you to explain the difference between locations highlighted in orange and those that are not highlighted on the web page.
> 
> Ah yes, I added the badge for "New". It should be live on site now.

I don't have any idea now. Just asking in case I would love to use it in the future.

**Comment by ruchernchong** [comment]
I will close the issue now that the question is being answered.

Thank you.
